import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { LogOutBtn } from "./LogoutBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <div>
            <Link href="/" className="logo">
              apple forum
            </Link>
            <Link href="/list">list</Link>
          </div>
          <div>
            {session ? (
              <span>
                {session.user.name} <LogOutBtn />
              </span>
            ) : (
              <LoginBtn />
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
